function smoothMesh = mesh2D_smoothMesh(meshToSmooth)

          
% Smooth mesh
[ vert,...
  etri,...
  tria,...
  tnum] = ...
  smooth2(meshToSmooth.vert, ...
          meshToSmooth.etri, ...
          meshToSmooth.tria, ...
          meshToSmooth.tnum);

% Update mesh structure
smoothMesh = meshToSmooth;
smoothMesh.vert = vert;
smoothMesh.etri = etri;
smoothMesh.tria = tria;
smoothMesh.tnum = tnum;

end